ALTER TABLE tickets
    ADD COLUMN IF NOT EXISTS resource_id BIGINT;

ALTER TABLE tickets
    ADD COLUMN IF NOT EXISTS location VARCHAR(150);

ALTER TABLE tickets
    ADD COLUMN IF NOT EXISTS requester_email VARCHAR(150) DEFAULT 'student@smartcampus.local';

ALTER TABLE tickets
    ADD COLUMN IF NOT EXISTS preferred_contact VARCHAR(150);

ALTER TABLE tickets
    ADD COLUMN IF NOT EXISTS assigned_technician_email VARCHAR(150);

ALTER TABLE tickets
    ADD COLUMN IF NOT EXISTS resolution_notes VARCHAR(1000);

ALTER TABLE tickets
    ADD COLUMN IF NOT EXISTS rejection_reason VARCHAR(255);

ALTER TABLE tickets
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

ALTER TABLE tickets
    ALTER COLUMN requester_email SET NOT NULL;

CREATE TABLE IF NOT EXISTS ticket_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL,
    author_email VARCHAR(150) NOT NULL,
    content VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_ticket_comments_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ticket_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    stored_file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(120) NOT NULL,
    file_size BIGINT NOT NULL,
    uploaded_by VARCHAR(150) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ticket_attachments_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE
);