CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(120) NOT NULL,
    role VARCHAR(40) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO app_users (email, password_hash, role)
SELECT 'student1@smartcampus.local', '$2y$10$N.uESOPZ4pMf4BwQ8rcone/JzYOhvVEOi/JRvM/RPHWt27CYYtxNK', 'USER'
WHERE NOT EXISTS (
    SELECT 1 FROM app_users WHERE email = 'student1@smartcampus.local'
);

INSERT INTO app_users (email, password_hash, role)
SELECT 'tech1@smartcampus.local', '$2y$10$N.uESOPZ4pMf4BwQ8rcone/JzYOhvVEOi/JRvM/RPHWt27CYYtxNK', 'TECHNICIAN'
WHERE NOT EXISTS (
    SELECT 1 FROM app_users WHERE email = 'tech1@smartcampus.local'
);

INSERT INTO app_users (email, password_hash, role)
SELECT 'admin@smartcampus.local', '$2y$10$N.uESOPZ4pMf4BwQ8rcone/JzYOhvVEOi/JRvM/RPHWt27CYYtxNK', 'ADMIN'
WHERE NOT EXISTS (
    SELECT 1 FROM app_users WHERE email = 'admin@smartcampus.local'
);
